# fly.toml app configuration file generated for pack-track on 2025-08-31T02:11:58-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pack-track'
primary_region = 'mia'

[build]
  dockerfile = 'Dockerfile'

[env]
  COOKIE_SECURE = 'true'
  DB_DIR = '/data'
  DB_FILE = 'packtrack.db'
  DB_PATH = '/data/packtrack.db'
  NODE_ENV = 'production'
  PORT = '3000'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '10s'
    method = 'get'
    path = '/api/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
